### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JohanChungus** [zeroone2numeral2/you-go-first#1]
I've been fill Hash and id on config.toml but its still not working please fix
![Screenshot_20230829-122027_Chrome](https://github.com/zeroone2numeral2/you-go-first/assets/113217515/ddbd6849-867b-47dc-8c24-aa1380de2908)

**Comment by zeroone2numeral2** [comment]
Which pyrogram version have you installed?

**Comment by JohanChungus** [comment]
pyrogram-repl

**Comment by JohanChungus** [comment]
> Which pyrogram version have you installed?

The version its 2.0.106

**Comment by zeroone2numeral2** [comment]
You have to install the python dependencies using the requirements file. I assume you didn't follow the instructions in the readme, if I'm mistaken feel free to reopen the issue. Try to read the readme

**Comment by JohanChungus** [comment]
> You have to install the python dependencies using the requirements file. I assume you didn't follow the instructions in the readme, if I'm mistaken feel free to reopen the issue. Try to read the readme

I already do it but still not working, maybe u need the script that can support new pyrogram version

**Comment by zeroone2numeral2** [comment]
The instructions in the readme say that requirements should be installed with `pip -r install requirements.txt`, which pins pyrogram's version to `1.2.9`. The program won't work with newer versions, but it should work with this one.  
So, either you've installed the requirements without the suggested command, or you've installed the requirements for a different python version than the one you're using to run the script. If you want to make sure you're using the correct packages and interpreter, run the script in a virtual environment

**Comment by JohanChungus** [comment]
> The instructions in the readme say that requirements should be installed with `pip -r install requirements.txt`, which pins pyrogram's version to `1.2.9`. The program won't work with newer versions, but it should work with this one. So, either you've installed the requirements without the suggested command, or you've installed the requirements for a different python version than the one you're using to run the script. If you want to make sure you're using the correct packages and interpreter, run the script in a virtual environment

`Can u update the script that allow use pyrogram new version:)`

**Comment by zeroone2numeral2** [comment]
Sorry, no time for that :(

**Comment by JohanChungus** [comment]
> Sorry, no time for that :(

What about now
